name: Deploy Full Stack

on:
  push:
    branches: [main]

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  PORT: 8200
  DISABLE_REDIS: true
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            sheila421/clientes-app:latest
            sheila421/clientes-app:${{ github.sha }}
          build-args: |
            POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
            SESSION_SECRET=${{ env.SESSION_SECRET }}
            NODE_ENV=${{ env.NODE_ENV }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: '201.23.3.86'  # IP direto ou use secrets.SSH_HOST
          username: 'aluno'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: '22'
          script: |
            #!/bin/bash
            set -e
            
            # 1. Cria rede e volume
            docker network create rede-da-sheila || true
            docker volume create pgdata || true

            # 2. Banco de dados PostgreSQL
            docker run -d --name sheila_postgres \
              --network rede-da-sheila \
              -e POSTGRES_PASSWORD='${{ env.POSTGRES_PASSWORD }}' \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_DB=connect_sphere \
              -v pgdata:/var/lib/postgresql/data \
              -p 5432:5432 \
              postgres:17

            # 3. Aplicação principal
            docker stop sheila_app || true
            docker rm sheila_app || true
            docker pull sheila421/clientes-app:latest
            
            docker run -d --name sheila_app \
              --network rede-da-sheila \
              -p 8200:8200 \
              -e PORT=8200 \
              -e POSTGRES_HOST=sheila_postgres \
              -e POSTGRES_PASSWORD='${{ env.POSTGRES_PASSWORD }}' \
              -e SESSION_SECRET='${{ env.SESSION_SECRET }}' \
              -e NODE_ENV=production \
              sheila421/clientes-app:latest

            # 4. Health check
            sleep 15
            curl -f http://localhost:8200/health || exit 1
