name: Deploy Full Stack

on:
  push:
    branches: [main]

env:
  # Variáveis de ambiente globais para o job.
  # Serão usadas no build da imagem Docker e passadas para o script de deploy SSH.
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  PORT: 8213
  DISABLE_REDIS: true
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest # O runner que executará o job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Clona o seu repositório

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Faz login no Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # PASSO DE DEBUG (REMOVIDO: Verify POSTGRES_PASSWORD secret - cumpriu sua função)

      - name: Build and push Docker image
        uses: docker/build-push-action@v6 # Constrói e envia a imagem Docker
        with:
          context: . # Usa o diretório raiz do repositório como contexto para o Dockerfile
          push: true
          tags: | # Define as tags para a imagem
            sheila421/clientes-app:latest 
            sheila421/clientes-app:${{ github.sha }} 
          build-args: | # Passa argumentos para o Dockerfile durante o build.
            POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
            SESSION_SECRET=${{ env.SESSION_SECRET }}
            NODE_ENV=${{ env.NODE_ENV }}
            PORT=${{ env.PORT }}
            DISABLE_REDIS=${{ env.DISABLE_REDIS }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1 # Conecta via SSH ao servidor e executa o script
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Se sua chave privada tiver uma passphrase, descomente a linha abaixo e crie a secret:
          # passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }} 
          
          # Variáveis de ambiente do job que serão passadas para o ambiente do script SSH.
          envs: |
            POSTGRES_PASSWORD
            SESSION_SECRET
            PORT
            DISABLE_REDIS
            NODE_ENV
          
          script: |
            #!/bin/bash
            set -e           # Aborta o script imediatamente se um comando falhar
            set -o pipefail  # Aborta o script se um comando em um pipe falhar

            echo "Iniciando deploy no servidor..."

            echo "Verificando/Criando rede Docker 'rede-da-sheila'..."
            docker network inspect rede-da-sheila >/dev/null 2>&1 || docker network create rede-da-sheila

            echo "Verificando/Criando volume Docker 'pgdata' para PostgreSQL..."
            docker volume create pgdata || true

            echo "Parando e removendo container PostgreSQL antigo (se existir)..."
            docker stop sheila_postgres || true
            docker rm sheila_postgres || true

            echo "Iniciando novo container PostgreSQL 'sheila_postgres' na porta 8214 do host..."
            docker run -d --name sheila_postgres --network rede-da-sheila \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_DB=connect_sphere \
              -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
              #-e POSTGRES_HOST_AUTH_METHOD=trust \ # <<-- REMOVIDO: Linha de debug de segurança (COMENTADA)
              -v pgdata:/var/lib/postgresql/data \
              -p 8214:5432 \
              postgres:17
            echo "PostgreSQL iniciado."

            # AGUARDANDO O POSTGRESQL (MUDANÇA: AGORA É UM SLEEP FIXO)
            echo "Aguardando um momento para o PostgreSQL inicializar completamente (15s)..."
            sleep 15 # Espera 15 segundos. Isso deve ser tempo suficiente para o DB iniciar.
            echo "PostgreSQL deve estar pronto agora."

            echo "Puxando a última imagem Docker da aplicação 'sheila421/clientes-app:latest'..."
            docker pull sheila421/clientes-app:latest

            echo "Parando e removendo container da aplicação antigo (se existir)..."
            docker stop sheila_app || true
            docker rm sheila_app || true

            echo "Iniciando novo container da aplicação 'sheila_app' na porta 8213 do host..."
            docker run -d --name sheila_app --network rede-da-sheila \
              -p 8213:8213 \
              -e PORT="${PORT}" \
              -e POSTGRES_HOST=sheila_postgres \
              -e POSTGRES_PORT=5432 \
              -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
              -e SESSION_SECRET="${SESSION_SECRET}" \
              -e NODE_ENV="${NODE_ENV}" \
              -e DISABLE_REDIS="${DISABLE_REDIS}" \
              sheila421/clientes-app:latest
            echo "Container da aplicação iniciado."
            
            echo "Aplicação disponível em http://137.184.213.189:8213" # IP do seu novo servidor
            echo "Deploy finalizado. Verifique os logs da aplicação diretamente no servidor se houver problemas."
            echo "Últimos logs da aplicação 'sheila_app' para referência:"
            docker logs sheila_app

            # OTIMIZAÇÃO: Limpeza de imagens Docker não usadas no servidor (apenas as que você tem controle)
            # Essas linhas estão comentadas e devem ser usadas com cautela, ou executadas manualmente no servidor
            # echo "Realizando limpeza de imagens Docker antigas e não referenciadas localmente..."
            # docker image prune -f # Remove imagens sem tags e as que não são usadas por containers rodando
            # docker builder prune -f # Limpa o cache de build do Docker no servidor