name: Deploy Clientes Application

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  NODE_ENV: production
  PORT: 8212
  DISABLE_REDIS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clientes-app:latest

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            #!/bin/bash
            set -e
            set -o pipefail
            
            # Criar rede Docker personalizada
            docker network create rede-da-sheila || true

            # Criar volume persistente para PostgreSQL
            docker volume create rede-da-sheila-postgres-data || true

            # Criar e iniciar o container PostgreSQL (se não existir)
            docker ps -a --filter "name=rede-da-sheila-postgres" --format '{{.Names}}' | grep -q rede-da-sheila-postgres || \
              docker run --name rede-da-sheila-postgres --network rede-da-sheila -p 5432:5432 \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
              -e POSTGRES_DB=connect_sphere \
              -v rede-da-sheila-postgres-data:/var/lib/postgresql/data \
              -d postgres:17

            # Parar e remover o container da aplicação antiga (se existir)
            docker stop rede-da-sheila-app || true
            docker rm rede-da-sheila-app || true

            # Puxar a última imagem do Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/clientes-app:latest

            # Criar e iniciar o novo container da aplicação
            docker run --name rede-da-sheila-app --network rede-da-sheila -p 8212:8212 \
              -e PORT=8212 \
              -e POSTGRES_HOST=rede-da-sheila-postgres \
              -e POSTGRES_PORT=5432 \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_DB=connect_sphere \
              -e POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
              -e DISABLE_REDIS=true \
              -e SESSION_SECRET='${{ secrets.SESSION_SECRET }}' \
              -e NODE_ENV=production \
              -d ${{ secrets.DOCKER_USERNAME }}/clientes-app:latest

            # Health check
            echo "Waiting for application to start..."
            timeout 120 bash -c 'while ! curl -sSf http://localhost:8212/health >/dev/null; do sleep 5; echo "Retrying..."; done' || \
              (echo "Application failed to start"; docker logs rede-da-sheila-app; exit 1)