name: Deploy Full Stack

on:
  push:
    branches: [main]

env:
  # Variáveis de ambiente (usando secrets)
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  PORT: 8200
  DISABLE_REDIS: true
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Login no Docker Hub (CORRIGIDO - usando secrets do repositório)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Secret de repositório
          password: ${{ secrets.DOCKER_PASSWORD }}   # Token de acesso

      # Passo 3: Build e push da imagem (CORRIGIDO - removido 'secrets:' desnecessário)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            sheila421/clientes-app:latest  # CORRIGIDO nome de usuário
            sheila421/clientes-app:${{ github.sha }}
          build-args: |  # Variáveis passadas como build-args
            POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
            SESSION_SECRET=${{ env.SESSION_SECRET }}
            NODE_ENV=${{ env.NODE_ENV }}

      # Passo 4: Deploy via SSH (CORRIGIDO - usando env corretamente)
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            set -e
            
            # 1. Cria rede e volume
            docker network create rede-da-sheila || true
            docker volume create pgdata || true

            # 2. Banco de dados PostgreSQL
            docker run -d --name sheila_postgres \
              --network rede-da-sheila \
              -e POSTGRES_PASSWORD='${{ env.POSTGRES_PASSWORD }}' \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_DB=connect_sphere \
              -v pgdata:/var/lib/postgresql/data \
              -p 5432:5432 \
              postgres:17

            # 3. Aplicação principal (CORRIGIDO nome da imagem)
            docker run -d --name sheila_app \
              --network rede-da-sheila \
              -p 8200:8200 \
              -e PORT=8200 \
              -e POSTGRES_HOST=sheila_postgres \
              -e POSTGRES_PASSWORD='${{ env.POSTGRES_PASSWORD }}' \
              -e SESSION_SECRET='${{ env.SESSION_SECRET }}' \
              -e NODE_ENV=production \
              sheila421/clientes-app:latest  # CORRIGIDO nome de usuário

            # 4. Health check
            sleep 15
            curl -f http://localhost:8200/health || exit 1
