name: Deploy Validation (No Server)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: production

jobs:
  validate-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Instalação de dependências (sem devDependencies)
      - name: Install dependencies
        run: npm install --omit=dev && npm cache clean --force

      # Passo 3: Build do projeto (se aplicável)
      - name: Build application
        run: npm run build --if-present && echo "Build completed"

      # Passo 4: Teste do container Docker (sem push)
      - name: Docker build test
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true  # Apenas carrega localmente, não envia para registry
          tags: local-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Passo 5: Validação final
      - name: Verify deployment package
        run: |
          echo "=== VALIDAÇÃO ==="
          echo "Arquivos no diretório:"
          ls -lh
          echo "Variáveis de ambiente:"
          printenv | grep -E 'NODE_ENV|POSTGRES_'
          echo "Container construído com sucesso!"
            # Health Check
            sleep 15
            docker ps --filter "name=sheila_app" --format "{{.Status}}" | grep -q "Up" || \
              (docker logs sheila_app && exit 1)
