name: Deploy TESTWE Application

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes unitários
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: Sheila724
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: Sheila724/clientes-app:latest

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Criar rede Docker personalizada (rede-da-sheila)
            docker network create rede-da-sheila || true

            # Criar volume persistente para PostgreSQL
            docker volume create rede-da-sheila-postgres-data || true

            # Criar e iniciar o container PostgreSQL (se não existir)
            docker ps -a --filter "name=sheila_postgres" --format '{{.Names}}' | grep -q sheila_postgres || \
              docker run --name sheila_postgres --network rede-da-sheila -p 6543:5432 \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD='@Teste123' \
              -e POSTGRES_DB=connect_sphere \
              -v rede-da-sheila-postgres-data:/var/lib/postgresql/data -d postgres:17

            # Parar e remover o container da aplicação antiga (se existir)
            docker stop sheila_app || true
            docker rm sheila_app || true

            # Puxar a última imagem do Docker Hub
            docker pull Sheila724/clientes-app:latest

            # Criar e iniciar o novo container da aplicação
            docker run --name sheila_app --network rede-da-sheila -p 8320:8200 \
              -e PORT=8200 \
              -e POSTGRES_HOST=sheila_postgres \
              -e POSTGRES_PORT=5432 \
              -e POSTGRES_PASSWORD='@Teste123' \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_DB=connect_sphere \
              -e DISABLE_REDIS=true \
              -e SESSION_SECRET='fionastarfred' \
              -d Sheila724/clientes-app:latest

