name: Deploy TESTWE Application

on:
  push:
    branches: [ main ]
  
  pull_request:
    types: [closed]
    branches: [ main ]

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  deploy:
    needs: test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: Sheila724/clientes-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            set -o pipefail
            
            # Rede e Volume
            docker network create rede-da-sheila || true
            docker volume create rede-da-sheila-postgres-data || true

            # PostgreSQL
            docker ps -a --filter "name=sheila_postgres" --format '{{.Names}}' | grep -q sheila_postgres || \
              docker run --name sheila_postgres --network rede-da-sheila -p 6543:5432 \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD='${{ env.POSTGRES_PASSWORD }}' \
              -e POSTGRES_DB=connect_sphere \
              -v rede-da-sheila-postgres-data:/var/lib/postgresql/data -d postgres:17

            # Aplicação
            docker stop sheila_app || true
            docker rm sheila_app || true
            docker pull Sheila724/clientes-app:latest
            
            docker run --name sheila_app --network rede-da-sheila -p 8320:8200 \
              -e PORT=8200 \
              -e POSTGRES_HOST=sheila_postgres \
              -e POSTGRES_PORT=5432 \
              -e POSTGRES_PASSWORD='${{ env.POSTGRES_PASSWORD }}' \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_DB=connect_sphere \
              -e DISABLE_REDIS=true \
              -e SESSION_SECRET='${{ env.SESSION_SECRET }}' \
              -d Sheila724/clientes-app:latest

            # Health Check
            sleep 15
            docker ps --filter "name=sheila_app" --format "{{.Status}}" | grep -q "Up" || \
              (docker logs sheila_app && exit 1)